_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  # WEIGHTS: /content/working/BoostTrack/external/weights/mot17_sbs_S50.pth

DATASETS:
  NAMES: ("MOT20",)
  TESTS: ("MOT20",)

OUTPUT_DIR: /content/Drive/Shareddrives/MyPrivateDrive/MOT20_ReID/Logs/
