_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone
  WEIGHTS: /kaggle/working/BoostTrack/external/mot17_sbs_S50.pth

DATASETS:
  NAMES: ("MOT20",)
  TESTS: ("MOT20",)

OUTPUT_DIR: fast_reid/logs/MOT20/sbs_S50
